server:
  port: 9096
spring:
  application:
    name: springboot-rmq-receiver
  rabbitmq:
    host: rabbitmq-cluster.rabbitmq-system.svc.cluster.local
    username: rabbitmq
    password: rabbitmq

management:
  endpoints:
    web:
      exposure:
        include: "*"      
